version: '3.7'

services:
    raffle-telegram-bot-develop:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - '8000:8000'
        restart: always
        command: tail -F anything