version: '3.7'

services:
    raffle-telegram-bot-production:
        build: .
        volumes:
            - ./database:/usr/src/app/database # database
        ports:
            - '8000:8000'
        restart: always